version: '2'
services:
  php:
    build: 
      context: .
      dockerfile: Web.Dockerfile
    ports:
      - "8585:80"
    depends_on:
      - db

  db:
    build:  
      context: .
      dockerfile: Db.Dockerfile
    ports:
      - "3306"
    volumes:
      - mysql_data_1:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD:root
volumes:
  mysql_data_1:
