---
- name: Deploy applications to Kubernetes
  hosts: localhost
#  become: yes
  tasks:
    - name: installer les prérequis
      pip:
        name:
          - terraform-install
        state: present

    - name:  Démarrer minikube
      shell: minikube start
#      register: minikube-sortie

    - name: Création de l'infrastructure
      terraform:
         project_path: ../terraform
         force_init: yes

